# Your workflow name.
name: Deploy to heroku and netlify

# Run workflow on every push to master branch.
on:
  push:
    branches: [main]
    paths:
      - "packages/server/**"
      - "packages/shared/**"
      - "packages/client/**"
      - "./Dockerfile"
      - "./.github/**"
  workflow_dispatch:
    branches: [main]

# Your workflows jobs.
jobs:
  build_server_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web

  deploy:
    runs-on: ubuntu-latest
    needs: [build_server_and_deploy]
    steps:
      - uses: actions/checkout@v2

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install
        working-directory: ./packages/client

      - name: Build client app
        run: pnpm build
        working-directory: ./packages/client
      #  your build commands
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: "--prod" #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          # working-directory: ./packages/client
